# Configurable variables
NUM_EPOCHS: 50
NOISE_DIMENSION: 50
BATCH_SIZE: 128
TRAIN_ON_GPU: True
PRINT_STATS_AFTER_BATCH: 50
OPTIMIZER_LR: 0.0002
OPTIMIZER_BETAS: [0.5, 0.999]
GENERATOR_OUTPUT_IMAGE_SHAPE: 784 # 28 * 28 * 1