name: Smoke Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Patch config.yaml
        run: |
          yq eval '
          .NUM_EPOCHS = 1 |
          .BATCH_SIZE = 128 |
          .TRAIN_ON_GPU = false
          ' -i config.yaml
    
      - name: Run smoke test
        run: bash scripts/run_train.sh